AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda function with cfn-response.
Resources:
  MyFunctionRole:
      Type: AWS::IAM::Role
      Properties:
         AssumeRolePolicyDocument:
            Version: '2012-10-17'
            Statement:
               - Effect: Allow
                 Principal:
                    Service: lambda.amazonaws.com
                 Action: sts:AssumeRole
         ManagedPolicyArns:
            - arn:aws:iam::aws:policy/AWSLambdaExecute
  MyCFFunction:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: nodejs12.x
      Role: !GetAtt 'MyFunctionRole.Arn'
      Handler: index.handler
      FunctionName: MyCFLambda
      Code:
        S3Bucket: sodaru-templates
        S3Key: index.zip
      Description: Invoke a function during stack creation.
      TracingConfig:
        Mode: Active
  CFSubscription:
    Type: 'AWS::SNS::Subscription'
    Properties:
      TopicArn: arn:aws:sns:ap-south-1:315143150079:MySnsTopic
      Endpoint: !GetAtt MyCFFunction.Arn
      Protocol: lambda