version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "aws-slack-alert"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-hfc95scbbyxd"
s3_prefix = "aws-slack-alert"
region = "ap-south-1"
confirm_changeset = true
notification-arns = ""
capabilities = "CAPABILITY_IAM"
parameter_overrides = ""

[dev]
stack_name = "sam"
s3_bucket = "aws_sam"
s3_prefix = "sam1"
region = "ap-south-1"
confirm_changeset = true
notification-arns = ""
capabilities = "CAPABILITY_IAM"
tags "Key1=Value1"
parameter_overrides = "slackurl=\"\""
