version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam2"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1iiscawbqckp0"
s3_prefix = "sam2"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
